project_id = "zujkxmcxnkpnktwcnkkk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "https://zujkxmcxnkpnktwcnkkk.supabase.co",
  "http://localhost:3000",
  "https://*.vercel.app",
  "https://*.netlify.app"
]
jwt_expiry = 3600
enable_signup = true
enable_manual_linking = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.send-notification-email]
verify_jwt = false

[functions.process-notifications]
verify_jwt = false