// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zujkxmcxnkpnktwcnkkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1amt4bWN4bmtwbmt0d2Nua2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0OTU2OTcsImV4cCI6MjA2NzA3MTY5N30.Ei6U80hOnrpH3j9l0y7_EUW7QIbSti8aU5qvINH_DhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});